package merotracker.repository;

import merotracker.model.Vehicle;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.web.bind.annotation.CrossOrigin;

import java.util.Optional;

/**
* Generated by Spring Data Generator on 08/04/2019
*/
@CrossOrigin
@RepositoryRestResource
public interface VehicleRepository extends JpaRepository<Vehicle, Integer> {
    Optional<Vehicle> findByPublicId(String publicId);
}
