package merotracker.repository;

import merotracker.model.VehiclePosition;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.web.bind.annotation.CrossOrigin;

/**
* Generated by Spring Data Generator on 08/04/2019
*/
@CrossOrigin
@RepositoryRestResource
public interface VehiclePositionRepository extends JpaRepository<VehiclePosition, Integer> {

}
